## Derived from https://raw.githubusercontent.com/actions/starter-workflows/refs/heads/main/ci/cmake-multi-platform.yml
name: CI

on:
  workflow_dispatch: {}
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        cpp_compiler: [g++, clang++, cl]
        include:
          - os: windows-latest
            cpp_compiler: cl
            preset: windows
          - os: ubuntu-latest
            cpp_compiler: g++
            preset: unix
          - os: ubuntu-latest
            cpp_compiler: clang++
            preset: unix
          - os: macos-latest
            cpp_compiler: clang++
            preset: unix
        exclude:
          - os: windows-latest
            cpp_compiler: g++
          - os: windows-latest
            cpp_compiler: clang++
          - os: ubuntu-latest
            cpp_compiler: cl
          - os: macos-latest
            cpp_compiler: cl
          - os: macos-latest
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false

    - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1
      if: ${{ matrix.os }} == 'windows-latest'

    - uses: Bacondish2023/setup-googletest@49065d1f7a6d21f6134864dd65980fe5dbe06c73 # v1.0.1

    - name: Configure CMake
      env:
        BUILD_DIR: ${{ github.workspace }}/build
      run: >
        echo "$BUILD_DIR"
        cmake -B "$BUILD_DIR"
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        --preset ${{ matrix.preset }}
        -S "${{ github.workspace }}"

    - name: Build
      env:
        BUILD_DIR: ${{ github.workspace }}/build
      run: >
        echo "$BUILD_DIR"
        cmake --build "$BUILD_DIR" --config ${{ matrix.build_type }}

    - name: Test
      env:
        BUILD_DIR: ${{ github.workspace }}/build
      run: >
        ctest --build-config ${{ matrix.build_type }} --rerun-failed --output-on-failure
