## Derived from https://raw.githubusercontent.com/actions/starter-workflows/refs/heads/main/ci/cmake-multi-platform.yml
name: CI

on:
  workflow_dispatch: {}
  pull_request: {}
  push: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        cpp_compiler: [g++, clang++, cl]
        include:
          - os: windows-latest
            cpp_compiler: cl
            preset: windows
          - os: ubuntu-latest
            cpp_compiler: g++
            preset: unix
          - os: ubuntu-latest
            cpp_compiler: clang++
            preset: unix
          - os: macos-latest
            cpp_compiler: clang++
            preset: unix
        exclude:
          - os: windows-latest
            cpp_compiler: g++
          - os: windows-latest
            cpp_compiler: clang++
          - os: ubuntu-latest
            cpp_compiler: cl
          - os: macos-latest
            cpp_compiler: cl
          - os: macos-latest
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - uses: ilammy/msvc-dev-cmd@v1
      if: ${{ matrix.os }} == 'windows-latest'

    - uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        --preset ${{ matrix.preset }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
