name: QEMU Tests

on:
  workflow_dispatch: {}
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm, aarch64, riscv64]
        include:
          - arch: arm
            qemu: qemu-arm
            triple: arm-linux-gnueabihf
          - arch: aarch64
            qemu: qemu-aarch64
            triple: aarch64-linux-gnu
          - arch: riscv64
            qemu: qemu-riscv64
            triple: riscv64-linux-gnu

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/${{ matrix.arch }}/build" >> "$GITHUB_OUTPUT"

    - name: Install QEMU and build tools
      run: |
        # sudo apt-get autopurge -y needrestart
        sudo apt-get update
        sudo apt-get install -y qemu-user cmake build-essential apt-file
        sudo apt-get install -y gcc-${{ matrix.triple }} g++-${{ matrix.triple }} libgtest-dev
        sudo apt-file update

    - name: Compiler Version
      run: |
        apt-file list g++-${{ matrix.triple }}
        /usr/bin/${{ matrix.triple }}-g++ --version

    - uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0

    - name: Configure CMake for ${{ matrix.arch }}
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
              -DCMAKE_CXX_COMPILER=${{ matrix.triple }}-g++ \
              -DCMAKE_CROSSCOMPILING=TRUE \
              -DCMAKE_SYSTEM_NAME=Linux \
              -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} \
              -DQEMU_RUN=${{ matrix.qemu }} .. \
              --preset qemu \
              -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Run tests with CTest and QEMU
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        ctest -V --timeout 300
          --build-config Release \
          --rerun-failed \
          --output-on-failure \
          --test-action test \
          --tests-regex ".*" \
          --overwrite MemoryCheckCommand=${{ matrix.qemu }} \
          --overwrite MemoryCheckCommandOptions="" \
          --overwrite MemoryCheckType=AddressSanitizer