name: CI Random Compiler Options

on:
  workflow_dispatch: {}
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # We want to see all results
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        # How many tests per workflow run
        test_combination: [1, 2, 3]

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Get All GCC Options
      id: get-options
      run: |
        # Get complete list of options
        ALL_OPTIONS=$(gcc --help -v 2>&1 | grep -o '\-[[:alpha:]][[:alnum:]-]*' | sort -u)
        echo "Found $(echo "$ALL_OPTIONS" | wc -l) unique compiler options"

        echo "ALL_OPTIONS<<EOF" >> $GITHUB_ENV
        echo "$ALL_OPTIONS" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        echo "all_options<<EOF" >> $GITHUB_OUTPUT
        echo "$ALL_OPTIONS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Generate Random Compiler Options
      id: compiler-options
      env:
        COMPILER_OPTIONS: ${{ env.ALL_OPTIONS }}
      run: |

        echo "Available options:"
        echo "$ALL_OPTIONS"

        readarray -t OPTIONS <<< "$COMPILER_OPTIONS"

        # Select a random optimization level
        OPT_LEVELS=(-O0 -O1 -O2 -O3 -Os -Ofast)
        BASE_OPT=${OPT_LEVELS[$RANDOM % ${#OPT_LEVELS[@]}]}

        TEST_DEFINES=(-D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -DRSTD_NONDETERMINISM)
        BASE_DEFINES=${TEST_DEFINES[$RANDOM % ${#TEST_DEFINES[@]}]}

        # Randomly select 5-15 compiler options
        NUM_OPTIONS=$((5 + RANDOM % 11))
        echo "Selected $NUM_OPTIONS options"
        SELECTED_OPTIONS="$BASE_OPT $BASE_DEFINES"

        for ((i=0; i<NUM_OPTIONS; i++)); do
          IDX=$((RANDOM % ${#OPTIONS[@]}))
          OPT="${OPTIONS[$IDX]}"

          # For options that need values, randomly generate them
          if [[ "$OPT" == *"="* ]]; then
            # For numeric values, generate random number
            OPT="${OPT}${RANDOM}"
          fi

          echo "Generated option $OPT"
          SELECTED_OPTIONS="$SELECTED_OPTIONS $OPT"
        done

        # Save to output
        echo "COMPILER_FLAGS=$SELECTED_OPTIONS" >> $GITHUB_ENV
      shell: bash

    - uses: Bacondish2023/setup-googletest@v1.0.1

    - name: Configure CMake
      id: configure
      env:
        BUILD_DIR: ${{ github.workspace }}/build
        COMPILER_FLAGS: ${{ env.COMPILER_FLAGS }}
      run: |
        echo "Using compiler flags: $COMPILER_FLAGS"
        cmake -B "$BUILD_DIR" \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_CXX_FLAGS="${COMPILER_FLAGS}" \
          -S "${{ github.workspace }}"

    - name: Build
      id: build
      env:
        BUILD_DIR: ${{ github.workspace }}/build
      run: cmake --build "$BUILD_DIR" --config ${{ matrix.build_type }}

    - name: Test
      if: steps.build.outcome == 'success'
      continue-on-error: true
      env:
        BUILD_DIR: ${{ github.workspace }}/build
      run: ctest --build-config ${{ matrix.build_type }} --rerun-failed --output-on-failure

    - name: Report Build Results
      if: always()
      env:
        COMPILER_FLAGS: ${{ env.compiler_flags }}
        CONFIGURE_RESULT: ${{ steps.configure.outcome }}
        BUILD_RESULT: ${{ steps.build.outcome }}
      run: |
        echo "Build Report"
        echo "============"
        echo "Compiler flags used:"
        echo "$COMPILER_FLAGS"
        echo ""
        echo "Configure result: $CONFIGURE_RESULT"
        echo "Build result: $BUILD_RESULT"

        # Store results in a file for potential analysis
        {
          echo "timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          echo "flags: $COMPILER_FLAGS"
          echo "configure_result: $CONFIGURE_RESULT"
          echo "build_result: $BUILD_RESULT"
          echo "---"
        } >> "${{ github.workspace }}/compiler_test_results.yml"

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: compiler-test-results
        path: ${{ github.workspace }}/compiler_test_results.yml